import { Injectable } from '@angular/core';
import { v4 as uuidv4 } from 'uuid';

@Injectable()
export class ProductService {
   products = [
    { productName: 'Puu', code: '1111', categoryName: 'Poltettava', unitType: 'MASS', color: 'green'},
    { productName: 'Multa', code: '2222',categoryName: 'Maatuva', unitType: 'MASS' , color: 'brown'},
    { productName: 'Öljy', code: '3333',categoryName: 'Ongelmajäte', unitType: 'VOLUME' , color: 'black'},
    { productName: 'Pesukone', code: '4444', categoryName: 'Metalli', unitType: 'PCS' , color: 'grey' },
    {
      productName: 'Paperi',
      code: '5555',
      categoryName: 'Kierrätettävä',
      unitType: 'VOLUME',
      color: 'blue'
    },
    {
      productName: 'Kotitalousjäte',
      code: '6666',
      categoryName: 'Poltettava',
      unitType: 'VOLUME',
      color: 'red'
    },
    {
      productName: 'Maalit',
      code: '7777',
      categoryName: 'Jatkokäsiteltävä ongelmajäte',
      unitType: 'VOLUME',
      color: 'pink'
    },
  ];

  getEventData() {
    const wasteOrigins = ['HOUSEHOLD', 'INDUSTRIAL', 'COMMERCIAL'];
    const contractNumbers = ['123456789', '987654321', '456123789'];
    const customers = ['John Doe', 'Jane Doe', 'Richard Roe'];
    const states = ['SHOPPING_CART_DRAFT', 'SHOPPING_CART', 'ORDER'];

    const collectionPoints = [
      { id: '1', identifier: 'A', name: 'Point A' },
      { id: '2', identifier: 'B', name: 'Point B' },
      { id: '3', identifier: 'C', name: 'Point C' },
      { id: '4', identifier: 'D', name: 'Point D' },
      { id: '5', identifier: 'E', name: 'Point E' },
    ];


    const transportCompanies = [
      'Kaukokuljetus',
      'Teron toimitus',
      'Kiitolinja',
      'UPS',
      'Nysse',
    ];

    const startDate = new Date(2023, 1, 1);
    const endDate = new Date(2023, 11, 31);
    const oneWeek = 7 * 24 * 60 * 60 * 1000;
    const oneDay = 24 * 60 * 60 * 1000;

    const cargoEvents = [];

    for (
      let date = startDate;
      date <= endDate;
      date = new Date(date.getTime() + oneDay)
    ) {
      const eventsPerWeek = Math.floor(Math.random() * 100) + 1;
      const eventsPerDay =  Math.floor(Math.random() * 10) + 1; // Change this to adjust the number of events per day

      for (let i = 0; i < eventsPerDay; i++) {
        const idx = Math.floor(Math.random() * this.products.length);
        const product = this.products[idx];
        const id = uuidv4();
        const transferId = uuidv4();
        const productId = uuidv4();
        const categoryId = uuidv4();
        const eventDate = new Date(
          date.getTime() + Math.floor(Math.random() * oneDay)
        );
        const transportCompany =
          transportCompanies[
            Math.floor(Math.random() * transportCompanies.length)
          ];
        const registerNumber = 'ABC-' + Math.floor(Math.random() * 1000);

        cargoEvents.push({
          id,
          transferId,
          productId,
          productCode: product.code,
          productName: product.productName,
          batchName: null,
          categoryName: product.categoryName,
          wasteOrigin:
            wasteOrigins[Math.floor(Math.random() * wasteOrigins.length)],
          contractNumber:
            contractNumbers[Math.floor(Math.random() * contractNumbers.length)],
          incoming: Math.random() > 0.5,
          outgoing: Math.random() <= 0.5,
          categoryId,
          totalPriceWithVat: Math.random() * 100,
          unitType: product.unitType,
          quantity: Math.floor(Math.random() * 100),
          weight: product.unitType === 'MASS' ? Math.random() * 100 : null,
          volume: product.unitType === 'VOLUME' ? Math.random() * 100 : null,
          customer: 'John Doe', // change this to randomly generated per event
          registerNumber,
          transportCompany,
          type: 'Transfer',
          state: states[Math.floor(Math.random() * states.length)],
          sourceCollectionPoint:
            collectionPoints[
              Math.floor(Math.random() * collectionPoints.length)
            ],
          targetCollectionPoint:
            collectionPoints[
              Math.floor(Math.random() * collectionPoints.length)
            ],
          fetchCollectionPoint:
            collectionPoints[
              Math.floor(Math.random() * collectionPoints.length)
            ],
          eventDate,
        });
      }
    }

    return cargoEvents;
  }

  getProductsData() {
    return [
      {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Toimittaja',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 65,
        category: 'Siirtoasiakirja',
        quantity: 24,
        inventoryStatus: 'INSTOCK',
        rating: 5,
        customer: 'Teppo Testaaja',
      },
      {
        id: '1001',
        code: 'f230fh0g3',
        name: 'Toimittaja',
        description: 'Product Description',
        image: 'black-watch.jpg',
        price: 72,
        category: 'Siirtoasiakirja',
        quantity: 61,
        inventoryStatus: 'OUTOFSTOCK',
        customer: 'Teppo Testaaja',
        rating: 4,
      },
      {
        id: '1002',
        code: 'f230fh0g3',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'blue-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        customer: 'Teppo Testaaja',
        rating: 3,
      },
      {
        id: '1003',
        code: 'f230fh0g3',
        name: 'Kuljetus T',
        description: 'Product Description',
        image: 'blue-t-shirt.jpg',
        price: 29,
        category: 'Kuorma',
        quantity: 25,
        inventoryStatus: 'INSTOCK',
        customer: 'Teppo Testaaja',
        rating: 5,
      },
      {
        id: '1004',
        code: 'h456wer53',
        name: 'Kuljetus T',
        description: 'Product Description',
        image: 'Kuljetus T.jpg',
        price: 15,
        category: 'Siirtoasiakirja',
        quantity: 73,
        inventoryStatus: 'INSTOCK',
        customer: 'Teppo Testaaja',
        rating: 4,
      },
      {
        id: '1005',
        code: 'h456wer53',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'brown-purse.jpg',
        price: 120,
        category: 'Siirtoasiakirja',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        customer: 'Teppo Testaaja',
        rating: 4,
      },
      {
        id: '1006',
        code: 'h456wer53',
        name: 'Chakra Kuljetus T',
        description: 'Product Description',
        image: 'chakra-Kuljetus T.jpg',
        price: 32,
        category: 'Siirtoasiakirja',
        quantity: 5,
        inventoryStatus: 'LOWSTOCK',
        customer: 'Teppo Testaaja',
        rating: 3,
      },
      {
        id: '1007',
        code: 'h456wer53',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'galaxy-earrings.jpg',
        price: 34,
        category: 'Siirtoasiakirja',
        quantity: 23,
        inventoryStatus: 'INSTOCK',
        customer: 'Teppo Testaaja',
        rating: 5,
      },
      {
        id: '1008',
        code: 'h456wer53',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'game-controller.jpg',
        price: 99,
        category: 'Kuorma',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1009',
        code: 'h456wer53',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'gaming-set.jpg',
        price: 299,
        category: 'Kuorma',
        quantity: 63,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 3,
      },
      {
        id: '1010',
        code: 'plb34234v',
        name: 'KuljetusNN',
        description: 'Product Description',
        image: 'gold-phone-case.jpg',
        price: 24,
        category: 'Siirtoasiakirja',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1011',
        code: 'plb34234v',
        name: 'KuljetusNN',
        description: 'Product Description',
        image: 'green-earbuds.jpg',
        price: 89,
        category: 'Kuorma',
        quantity: 23,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1012',
        code: 'plb34234v',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'green-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 74,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 5,
      },
      {
        id: '1013',
        code: 'plb34234v',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'grey-t-shirt.jpg',
        price: 48,
        category: 'Kuorma',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        customer: 'Kalle Kuski',
        rating: 3,
      },
      {
        id: '1014',
        code: 'plb34234v',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'KuljetusM.jpg',
        price: 175,
        category: 'Kuorma',
        quantity: 8,
        inventoryStatus: 'LOWSTOCK',
        customer: 'Kalle Kuski',
        rating: 5,
      },
      {
        id: '1015',
        code: 'plb34234v',
        name: 'Light KuljetusM',
        description: 'Product Description',
        image: 'light-green-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 34,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1016',
        code: 'plb34234v',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'lime-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 12,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 3,
      },
      {
        id: '1017',
        code: 'plb34234v',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'mini-speakers.jpg',
        price: 85,
        category: 'Kuorma',
        quantity: 42,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1018',
        code: '09zx9c0zc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'painted-phone-case.jpg',
        price: 56,
        category: 'Siirtoasiakirja',
        quantity: 41,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 5,
      },
      {
        id: '1019',
        code: '09zx9c0zc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'pink-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 63,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1020',
        code: '09zx9c0zc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'pink-purse.jpg',
        price: 110,
        category: 'Siirtoasiakirja',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1021',
        code: '09zx9c0zc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'purple-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 6,
        inventoryStatus: 'LOWSTOCK',
        customer: 'Kalle Kuski',
        rating: 3,
      },
      {
        id: '1022',
        code: '09zx9c0zc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'purple-gemstone-necklace.jpg',
        price: 45,
        category: 'Siirtoasiakirja',
        quantity: 62,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1023',
        code: '09zx9c0zc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'purple-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        customer: 'Kalle Kuski',
        rating: 5,
      },
      {
        id: '1024',
        code: '09zx9c0zc',
        name: 'KuljetusT',
        description: 'Product Description',
        image: 'KuljetusT.jpg',
        price: 64,
        category: 'Kuorma',
        quantity: 0,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1025',
        code: 'nbm5mv45n',
        name: 'KuljetusT',
        description: 'Product Description',
        image: 'KuljetusT.jpg',
        price: 78,
        category: 'Kuorma',
        quantity: 52,
        inventoryStatus: 'INSTOCK',
        customer: 'Kalle Kuski',
        rating: 4,
      },
      {
        id: '1026',
        code: 'nbm5mv45n',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'teal-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 3,
        inventoryStatus: 'LOWSTOCK',
        customer: 'Kalle Kuski',
        rating: 3,
      },
      {
        id: '1027',
        code: 'nbm5mv45n',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'yellow-earbuds.jpg',
        price: 89,
        category: 'Kuorma',
        quantity: 35,
        inventoryStatus: 'INSTOCK',
        customer: 'Ykä yrittäjä',
        rating: 3,
      },
      {
        id: '1028',
        code: 'tx125ck42',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'yoga-mat.jpg',
        price: 20,
        category: 'Siirtoasiakirja',
        quantity: 15,
        inventoryStatus: 'INSTOCK',
        customer: 'Ykä yrittäjä',
        rating: 5,
      },
      {
        id: '1029',
        code: 'nbm5mv45n',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'yoga-set.jpg',
        price: 20,
        category: 'Siirtoasiakirja',
        quantity: 25,
        inventoryStatus: 'INSTOCK',
        customer: 'Ykä yrittäjä',
        rating: 8,
      },
    ];
  }

  getProductsWithOrdersData() {
    return [
      {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Toimittaja',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 65,
        category: 'Siirtoasiakirja',
        quantity: 24,
        inventoryStatus: 'INSTOCK',
        rating: 5,
        orders: [
          {
            id: '1000-0',
            productCode: 'f230fh0g3',
            date: '2020-09-13',
            amount: 65,
            quantity: 1,
            customer: 'David James',
            status: 'PENDING',
          },
          {
            id: '1000-1',
            productCode: 'f230fh0g3',
            date: '2020-05-14',
            amount: 130,
            quantity: 2,
            customer: 'Leon Rodrigues',
            status: 'DELIVERED',
          },
          {
            id: '1000-2',
            productCode: 'f230fh0g3',
            date: '2019-01-04',
            amount: 65,
            quantity: 1,
            customer: 'Juan Alejandro',
            status: 'RETURNED',
          },
          {
            id: '1000-3',
            productCode: 'f230fh0g3',
            date: '2020-09-13',
            amount: 195,
            quantity: 3,
            customer: 'Claire Morrow',
            status: 'CANCELLED',
          },
        ],
      },
      {
        id: '1001',
        code: 'nvklal433',
        name: 'Toimittaja',
        description: 'Product Description',
        image: 'black-watch.jpg',
        price: 72,
        category: 'Siirtoasiakirja',
        quantity: 61,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [
          {
            id: '1001-0',
            productCode: 'nvklal433',
            date: '2020-05-14',
            amount: 72,
            quantity: 1,
            customer: 'Maisha Jefferson',
            status: 'DELIVERED',
          },
          {
            id: '1001-1',
            productCode: 'nvklal433',
            date: '2020-02-28',
            amount: 144,
            quantity: 2,
            customer: 'Octavia Murillo',
            status: 'PENDING',
          },
        ],
      },
      {
        id: '1002',
        code: 'zz21cz3c1',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'blue-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
        orders: [
          {
            id: '1002-0',
            productCode: 'zz21cz3c1',
            date: '2020-07-05',
            amount: 79,
            quantity: 1,
            customer: 'Stacey Leja',
            status: 'DELIVERED',
          },
          {
            id: '1002-1',
            productCode: 'zz21cz3c1',
            date: '2020-02-06',
            amount: 79,
            quantity: 1,
            customer: 'Ashley Wickens',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1003',
        code: '244wgerg2',
        name: 'Kuljetus T',
        description: 'Product Description',
        image: 'blue-t-shirt.jpg',
        price: 29,
        category: 'Kuorma',
        quantity: 25,
        inventoryStatus: 'INSTOCK',
        rating: 5,
        orders: [],
      },
      {
        id: '1004',
        code: 'h456wer53',
        name: 'Kuljetus T',
        description: 'Product Description',
        image: 'Kuljetus T.jpg',
        price: 15,
        category: 'Siirtoasiakirja',
        quantity: 73,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [
          {
            id: '1004-0',
            productCode: 'h456wer53',
            date: '2020-09-05',
            amount: 60,
            quantity: 4,
            customer: 'Mayumi Misaki',
            status: 'PENDING',
          },
          {
            id: '1004-1',
            productCode: 'h456wer53',
            date: '2019-04-16',
            amount: 2,
            quantity: 30,
            customer: 'Francesco Salvatore',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1005',
        code: 'av2231fwg',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'brown-purse.jpg',
        price: 120,
        category: 'Siirtoasiakirja',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 4,
        orders: [
          {
            id: '1005-0',
            productCode: 'av2231fwg',
            date: '2020-01-25',
            amount: 120,
            quantity: 1,
            customer: 'Isabel Sinclair',
            status: 'RETURNED',
          },
          {
            id: '1005-1',
            productCode: 'av2231fwg',
            date: '2019-03-12',
            amount: 240,
            quantity: 2,
            customer: 'Lionel Clifford',
            status: 'DELIVERED',
          },
          {
            id: '1005-2',
            productCode: 'av2231fwg',
            date: '2019-05-05',
            amount: 120,
            quantity: 1,
            customer: 'Cody Chavez',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1006',
        code: 'bib36pfvm',
        name: 'Chakra Kuljetus T',
        description: 'Product Description',
        image: 'chakra-Kuljetus T.jpg',
        price: 32,
        category: 'Siirtoasiakirja',
        quantity: 5,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
        orders: [
          {
            id: '1006-0',
            productCode: 'bib36pfvm',
            date: '2020-02-24',
            amount: 32,
            quantity: 1,
            customer: 'Arvin Darci',
            status: 'DELIVERED',
          },
          {
            id: '1006-1',
            productCode: 'bib36pfvm',
            date: '2020-01-14',
            amount: 64,
            quantity: 2,
            customer: 'Izzy Jones',
            status: 'PENDING',
          },
        ],
      },
      {
        id: '1007',
        code: 'mbvjkgip5',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'galaxy-earrings.jpg',
        price: 34,
        category: 'Siirtoasiakirja',
        quantity: 23,
        inventoryStatus: 'INSTOCK',
        rating: 5,
        orders: [
          {
            id: '1007-0',
            productCode: 'mbvjkgip5',
            date: '2020-06-19',
            amount: 34,
            quantity: 1,
            customer: 'Jennifer Smith',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1008',
        code: 'vbb124btr',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'game-controller.jpg',
        price: 99,
        category: 'Kuorma',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        rating: 4,
        orders: [
          {
            id: '1008-0',
            productCode: 'vbb124btr',
            date: '2020-01-05',
            amount: 99,
            quantity: 1,
            customer: 'Jeanfrancois David',
            status: 'DELIVERED',
          },
          {
            id: '1008-1',
            productCode: 'vbb124btr',
            date: '2020-01-19',
            amount: 198,
            quantity: 2,
            customer: 'Ivar Greenwood',
            status: 'RETURNED',
          },
        ],
      },
      {
        id: '1009',
        code: 'cm230f032',
        name: 'Kuljetus kk',
        description: 'Product Description',
        image: 'gaming-set.jpg',
        price: 299,
        category: 'Kuorma',
        quantity: 63,
        inventoryStatus: 'INSTOCK',
        rating: 3,
        orders: [
          {
            id: '1009-0',
            productCode: 'cm230f032',
            date: '2020-06-24',
            amount: 299,
            quantity: 1,
            customer: 'Kadeem Mujtaba',
            status: 'PENDING',
          },
          {
            id: '1009-1',
            productCode: 'cm230f032',
            date: '2020-05-11',
            amount: 299,
            quantity: 1,
            customer: 'Ashley Wickens',
            status: 'DELIVERED',
          },
          {
            id: '1009-2',
            productCode: 'cm230f032',
            date: '2019-02-07',
            amount: 299,
            quantity: 1,
            customer: 'Julie Johnson',
            status: 'DELIVERED',
          },
          {
            id: '1009-3',
            productCode: 'cm230f032',
            date: '2020-04-26',
            amount: 299,
            quantity: 1,
            customer: 'Tony Costa',
            status: 'CANCELLED',
          },
        ],
      },
      {
        id: '1010',
        code: 'plb34234v',
        name: 'KuljetusNN',
        description: 'Product Description',
        image: 'gold-phone-case.jpg',
        price: 24,
        category: 'Siirtoasiakirja',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 4,
        orders: [
          {
            id: '1010-0',
            productCode: 'plb34234v',
            date: '2020-02-04',
            amount: 24,
            quantity: 1,
            customer: 'James Butt',
            status: 'DELIVERED',
          },
          {
            id: '1010-1',
            productCode: 'plb34234v',
            date: '2020-05-05',
            amount: 48,
            quantity: 2,
            customer: 'Josephine Darakjy',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1011',
        code: '4920nnc2d',
        name: 'KuljetusNN',
        description: 'Product Description',
        image: 'green-earbuds.jpg',
        price: 89,
        category: 'Kuorma',
        quantity: 23,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [
          {
            id: '1011-0',
            productCode: '4920nnc2d',
            date: '2020-06-01',
            amount: 89,
            quantity: 1,
            customer: 'Art Venere',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1012',
        code: '250vm23cc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'green-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 74,
        inventoryStatus: 'INSTOCK',
        rating: 5,
        orders: [
          {
            id: '1012-0',
            productCode: '250vm23cc',
            date: '2020-02-05',
            amount: 49,
            quantity: 1,
            customer: 'Lenna Paprocki',
            status: 'DELIVERED',
          },
          {
            id: '1012-1',
            productCode: '250vm23cc',
            date: '2020-02-15',
            amount: 49,
            quantity: 1,
            customer: 'Donette Foller',
            status: 'PENDING',
          },
        ],
      },
      {
        id: '1013',
        code: 'fldsmn31b',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'grey-t-shirt.jpg',
        price: 48,
        category: 'Kuorma',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 3,
        orders: [
          {
            id: '1013-0',
            productCode: 'fldsmn31b',
            date: '2020-04-01',
            amount: 48,
            quantity: 1,
            customer: 'Simona Morasca',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1014',
        code: 'waas1x2as',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'KuljetusM.jpg',
        price: 175,
        category: 'Kuorma',
        quantity: 8,
        inventoryStatus: 'LOWSTOCK',
        rating: 5,
        orders: [
          {
            id: '1014-0',
            productCode: 'waas1x2as',
            date: '2020-05-15',
            amount: 175,
            quantity: 1,
            customer: 'Lenna Paprocki',
            status: 'DELIVERED',
          },
          {
            id: '1014-1',
            productCode: 'waas1x2as',
            date: '2020-01-02',
            amount: 175,
            quantity: 1,
            customer: 'Donette Foller',
            status: 'CANCELLED',
          },
        ],
      },
      {
        id: '1015',
        code: 'vb34btbg5',
        name: 'Light KuljetusM',
        description: 'Product Description',
        image: 'light-green-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 34,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [
          {
            id: '1015-0',
            productCode: 'vb34btbg5',
            date: '2020-07-02',
            amount: 98,
            quantity: 2,
            customer: 'Mitsue Tollner',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1016',
        code: 'k8l6j58jl',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'lime-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 12,
        inventoryStatus: 'INSTOCK',
        rating: 3,
        orders: [],
      },
      {
        id: '1017',
        code: 'v435nn85n',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'mini-speakers.jpg',
        price: 85,
        category: 'Kuorma',
        quantity: 42,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [
          {
            id: '1017-0',
            productCode: 'v435nn85n',
            date: '2020-07-12',
            amount: 85,
            quantity: 1,
            customer: 'Minna Amigon',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1018',
        code: '09zx9c0zc',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'painted-phone-case.jpg',
        price: 56,
        category: 'Siirtoasiakirja',
        quantity: 41,
        inventoryStatus: 'INSTOCK',
        rating: 5,
        orders: [
          {
            id: '1018-0',
            productCode: '09zx9c0zc',
            date: '2020-07-01',
            amount: 56,
            quantity: 1,
            customer: 'Abel Maclead',
            status: 'DELIVERED',
          },
          {
            id: '1018-1',
            productCode: '09zx9c0zc',
            date: '2020-05-02',
            amount: 56,
            quantity: 1,
            customer: 'Minna Amigon',
            status: 'RETURNED',
          },
        ],
      },
      {
        id: '1019',
        code: 'mnb5mb2m5',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'pink-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 63,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [],
      },
      {
        id: '1020',
        code: 'r23fwf2w3',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'pink-purse.jpg',
        price: 110,
        category: 'Siirtoasiakirja',
        quantity: 0,
        inventoryStatus: 'OUTOFSTOCK',
        rating: 4,
        orders: [
          {
            id: '1020-0',
            productCode: 'r23fwf2w3',
            date: '2020-05-29',
            amount: 110,
            quantity: 1,
            customer: 'Kiley Caldarera',
            status: 'DELIVERED',
          },
          {
            id: '1020-1',
            productCode: 'r23fwf2w3',
            date: '2020-02-11',
            amount: 220,
            quantity: 2,
            customer: 'Graciela Ruta',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1021',
        code: 'pxpzczo23',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'purple-band.jpg',
        price: 79,
        category: 'Siirtoasiakirja',
        quantity: 6,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
        orders: [
          {
            id: '1021-0',
            productCode: 'pxpzczo23',
            date: '2020-02-02',
            amount: 79,
            quantity: 1,
            customer: 'Cammy Albares',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1022',
        code: '2c42cb5cb',
        name: 'KuljetusM',
        description: 'Product Description',
        image: 'purple-gemstone-necklace.jpg',
        price: 45,
        category: 'Siirtoasiakirja',
        quantity: 62,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [
          {
            id: '1022-0',
            productCode: '2c42cb5cb',
            date: '2020-06-29',
            amount: 45,
            quantity: 1,
            customer: 'Mattie Poquette',
            status: 'DELIVERED',
          },
          {
            id: '1022-1',
            productCode: '2c42cb5cb',
            date: '2020-02-11',
            amount: 135,
            quantity: 3,
            customer: 'Meaghan Garufi',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1023',
        code: '5k43kkk23',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'purple-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 2,
        inventoryStatus: 'LOWSTOCK',
        rating: 5,
        orders: [
          {
            id: '1023-0',
            productCode: '5k43kkk23',
            date: '2020-04-15',
            amount: 49,
            quantity: 1,
            customer: 'Gladys Rim',
            status: 'RETURNED',
          },
        ],
      },
      {
        id: '1024',
        code: 'lm2tny2k4',
        name: 'KuljetusT',
        description: 'Product Description',
        image: 'KuljetusT.jpg',
        price: 64,
        category: 'Kuorma',
        quantity: 0,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [],
      },
      {
        id: '1025',
        code: 'nbm5mv45n',
        name: 'KuljetusT',
        description: 'Product Description',
        image: 'KuljetusT.jpg',
        price: 78,
        category: 'Kuorma',
        quantity: 52,
        inventoryStatus: 'INSTOCK',
        rating: 4,
        orders: [
          {
            id: '1025-0',
            productCode: 'nbm5mv45n',
            date: '2020-02-19',
            amount: 78,
            quantity: 1,
            customer: 'Yuki Whobrey',
            status: 'DELIVERED',
          },
          {
            id: '1025-1',
            productCode: 'nbm5mv45n',
            date: '2020-05-21',
            amount: 78,
            quantity: 1,
            customer: 'Fletcher Flosi',
            status: 'PENDING',
          },
        ],
      },
      {
        id: '1026',
        code: 'zx23zc42c',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'teal-t-shirt.jpg',
        price: 49,
        category: 'Kuorma',
        quantity: 3,
        inventoryStatus: 'LOWSTOCK',
        rating: 3,
        orders: [
          {
            id: '1026-0',
            productCode: 'zx23zc42c',
            date: '2020-04-24',
            amount: 98,
            quantity: 2,
            customer: 'Bette Nicka',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1027',
        code: 'acvx872gc',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'yellow-earbuds.jpg',
        price: 89,
        category: 'Kuorma',
        quantity: 35,
        inventoryStatus: 'INSTOCK',
        rating: 3,
        orders: [
          {
            id: '1027-0',
            productCode: 'acvx872gc',
            date: '2020-01-29',
            amount: 89,
            quantity: 1,
            customer: 'Veronika Inouye',
            status: 'DELIVERED',
          },
          {
            id: '1027-1',
            productCode: 'acvx872gc',
            date: '2020-06-11',
            amount: 89,
            quantity: 1,
            customer: 'Willard Kolmetz',
            status: 'DELIVERED',
          },
        ],
      },
      {
        id: '1028',
        code: 'tx125ck42',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'yoga-mat.jpg',
        price: 20,
        category: 'Siirtoasiakirja',
        quantity: 15,
        inventoryStatus: 'INSTOCK',
        rating: 5,
        orders: [],
      },
      {
        id: '1029',
        code: 'gwuby345v',
        name: 'KuljetusS',
        description: 'Product Description',
        image: 'yoga-set.jpg',
        price: 20,
        category: 'Siirtoasiakirja',
        quantity: 25,
        inventoryStatus: 'INSTOCK',
        rating: 8,
        orders: [
          {
            id: '1029-0',
            productCode: 'gwuby345v',
            date: '2020-02-14',
            amount: 4,
            quantity: 80,
            customer: 'Maryann Royster',
            status: 'DELIVERED',
          },
        ],
      },
    ];
  }

  getProductsMini() {
    return Promise.resolve(this.getProductsData().slice(0, 5));
  }

  getProductsSmall() {
    return Promise.resolve(this.getProductsData().slice(0, 10));
  }
  public getProductGroups() {
    return this.products;
  }

  getProducts() {
    return Promise.resolve(this.getProductsData());
  }

  getProductsWithOrdersSmall() {
    return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
  }

  getProductsWithOrders() {
    return Promise.resolve(this.getProductsWithOrdersData());
  }

  getEventDataRows() {
    return Promise.resolve(this.getEventData());
  }
}
